### ISSUE TITLE
기능구현 - 관리자/고객센터/공지사항

### ISSUE THREAD

**Issue by mintchoc31** [sloth0705/Kmarket#172]
<공지사항 목록>

- [ ] - 공지사항 유형별 목록 출력하기(공지사항 유형은 스토리보드 v1.4 No 4-3 참고)

- [ ] - 공지사항 유형 선택할 때 마다 목록 갱신 

- [ ] 선택삭제 :  체크박스 선택한 글 선택삭제

관리
- [ ] - 삭제 : 확인 대화상자 출력후 삭제

- [ ] - 수정 : 글수정 화면으로 이동

- [ ]  페이지 번호: 10개씩 공지사항 출력

- [ ]  작성하기: 작성하기 페이지로 이동

<공지사항 보기>

삭제
- [ ]  해당 공지사항 삭제
- [ ]  사용자 확인 대화상자 출력

수정
- [ ]  공지사항 수정화면 이동

목록
- [ ]  공지사항 목록 이동

<공지사항 작성>

작성
- [ ]  공지사항 유형 선택 (공지사항 유형은 스토리보드 No 4-3 참고)
- [ ] 공지사항 제목 작성
- [ ] 공지사항 내용 작성

취소
- [ ] 공지사항 목록 이동

등록
- [ ] 공지사항 테이블 INSERT

<공지사항 수정>

수정

- [ ] 유형 기본 선택
- [ ] 제목 기본 입력
- [ ] 내용 기본 입력

취소
- [ ] 공지사항 보기 이동

수정
- [ ] 테이블 UPDATE

**Comment by BSHaRu** [comment]
notice list, write, modify 다 cs에 구현 되어 있음
-> 할 필요 없이 그냥 해당 controller랑 view page를 쓰고 admin에 맞춰 조금만 수정 하면 될 듯
